### ISSUE TITLE
Styling The Pickerpage Listview

### ISSUE THREAD

**Issue by rifkirinaldi** [NativeScript/nativescript-picker#38]
Hi, i have no problem styling the action bar using 
PickerPage ActionBar { ....  }

But i can't find a way to do that on PickerPage ListView items , because the items text is so small and no-padding

PickerPage ListView { 
    padding : 20;  not work
}
PickerPage ListView item { 
    padding : 20;  not work
}

any help will be appreciated, thank you

**Comment by DimitarTodorov** [comment]
Hi @rifkirinaldi 

In order to set styles to items of the picker you should implement itemTemplate, then set the desired css class to the element in the template and styles will be applied correctly. 
##### Here is an example how a simple padding can be added to picker items in the getting-started example of our demo app:
`getting-started-page.xml`
```
<GridLayout rows="50, *">
	<picker:PickerField hint="Click here" padding="10" pickerOpened="pickerOpened" pickerClosed="pickerClosed" items="{{ pickerItems }}" >
		<picker:PickerField.itemTemplate>
			<Label text="Picker item" class="picker-item"></Label>
		</picker:PickerField.itemTemplate>
	</picker:PickerField>
</GridLayout>
```

`app.css`
```
.picker-item { 
    padding: 20;
}
```
Also you can take a look at the styling example for more advanced picker customisation.
